apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observatory-prod

resources:
  - ../../base

replicas:
  - name: observatory
    count: 1

images:
  - name: observatory
    newName: quay.io/observatory/observatory
    newTag: latest
