apiVersion: v1
kind: Secret
metadata:
  name: observatory-secrets
  labels:
    app.kubernetes.io/name: observatory
type: Opaque
stringData:
  OBSERVATORY_GITLAB_TOKEN: ""
  OBSERVATORY_GITHUB_TOKEN: ""
  OBSERVATORY_API_KEY: ""
